### PR TITLE
 moves some settings to DevOps Variable groups

### PR DESCRIPTION
**Pull request by cicorias**
still need to agree on what / how to handle the CD pipeline via documentation. As the K8 tasks all require a serviceEndpoint / Container Registry connection.

```
                                "containerRegistryType": "Azure Container Registry",
                                "dockerRegistryEndpoint": "",
                                "azureSubscriptionEndpoint": "",
                                "azureContainerRegistry": "agogoscr.azurecr.io",
```

### CODE REVIEW

**Comment by cicorias** [comment]
@sayar  can you confirm how to deal with IF they supply an ACR in manifest.json  - or can we move this to pure HOWTO in the documentation?  In other words, generate always depends upon Variable groups in Azure DevOps - and there is always a way to override via additional `variables: name: .. value: ... ` if you see the files in this PR you can see the narrative about that.

```
                                "containerRegistryType": "Azure Container Registry",
                                "dockerRegistryEndpoint": "",
                                "azureSubscriptionEndpoint": "",
                                "azureContainerRegistry": "agogoscr.azurecr.io",
```

**Comment by sayar** [comment]
> @sayar can you confirm how to deal with IF they supply an ACR in manifest.json - or can we move this to pure HOWTO in the documentation? In other words, generate always depends upon Variable groups in Azure DevOps - and there is always a way to override via additional `variables: name: .. value: ... ` if you see the files in this PR you can see the narrative about that.
> 
> ```
>                                 "containerRegistryType": "Azure Container Registry",
>                                 "dockerRegistryEndpoint": "",
>                                 "azureSubscriptionEndpoint": "",
>                                 "azureContainerRegistry": "agogoscr.azurecr.io",
> ```

@cicorias IMO, we should recommend using variable groups versus injecting variables into the yaml everywhere and move to pure doc. The CD still needs to be manually imported using the DevOps UI so regardless if we inject the variables or if we use variable groups, users will still need to do a click per task to get it working, might as well recommend variable groups there too.

**Comment by sayar** [comment]
@cicorias alternatively, we can add a flag in the manifest to inject or use variable groups but IMO variable groups are better. Our current project has 4 different agogosml projects that all push images to the same ACR instance, variable groups would help a lot!

**Comment by sayar** [comment]
@cicorias and I discussed this offline. Ready to switch this PR from draft and merge.

**Pull request merged**
