### PR TITLE
Switch OSS Project to YAML Pipelines

### PR DESCRIPTION
**Pull request by sayar**
Test Pipeline for Python Library: https://dev.azure.com/csedevil/agogosml/_build?definitionId=77
Test Pipeline for CLI: https://dev.azure.com/csedevil/agogosml/_build?definitionId=75

### CODE REVIEW

**Comment by cicorias** [comment]
looking now - will be running in different AZ Pipeline

**Comment by cicorias** [comment]
Can you look at https://github.com/Microsoft/agogosml/pull/271 in place of this?

**Comment by cicorias** [comment]
also tested here: 

https://dev.azure.com/scicoria-ms/ago2/_build/results?buildId=92

https://dev.azure.com/scicoria-ms/ago2/_build/results?buildId=93

**Comment by sayar** [comment]
Now superseded by #271

**Pull request closed without merging**
